AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a Ubuntu Server 24.04 LTS (HVM) (64_x86) on EC2 in us-east-1 region for the Bastionhosts server to connect MySQL database

Parameters:
  NameOfService:
    Description: The name of the service this stack is to be used for
    Type: String
    Default: Bastionhost
  DeploymentBucket:
    Description: Name of the deployment bucket
    Type: String
    Default: dev-wordpress-setup-lab-1
  EnvironmentName:
    Description: Name of the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - test
  InstanceTypeParam:
    Description: Type of the EC2 instance
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
Mappings:
  RegionAMIConfig:
    us-east-1:
      AMI: ami-04b70fa74e45c3917
    us-east-2:
      AMI: ami-09040d770ffe2224f
    ap-south-1:
      AMI: ami-0f58b397bc5c1f2e8
Resources:
  BastionhostServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParam
      ImageId: !FindInMap
        - RegionAMIConfig
        - !Ref AWS::Region
        - AMI
      Monitoring: true
      IamInstanceProfile: !ImportValue
        Fn::Sub: ${EnvironmentName}-ec2-instance-profile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          Description: Primary network interface
          DeviceIndex: 0
          GroupSet:
            - !ImportValue
              Fn::Sub: ${EnvironmentName}-ec2-security-group-id
          SubnetId: !ImportValue
            Fn::Sub: ${EnvironmentName}-public-subnet1-id
      Tags:
        - Key: Name
          Value: !Ref NameOfService
        - Key: RegionName
          Value: !Ref AWS::Region
        - Key: Environment
          Value: !Ref EnvironmentName
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          apt update -y
          apt upgrade -y
          apt install mysql-client -y
          apt install python3-pip unzip less -y
          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          ./aws/install
          rm -r awscliv2.zip
          aws s3 cp s3://${DeploymentBucket}/wordpress-site/bastionhost/ /home/ubuntu/wordpress-site/bastionhost/ --recursive
          chmod +x /home/ubuntu/wordpress-site/bastionhost/bastionhost_setup.sh
          /home/ubuntu/wordpress-site/bastionhost/bastionhost_setup.sh
          
Outputs:
  AccountId:
    Description: AWS Account ID
    Value: !Ref AWS::AccountId
  RegionName:
    Description: AWS Region Name
    Value: !Ref AWS::Region
  StackId:
    Description: Current Stack ID
    Value: !Ref AWS::StackId
  StackName:
    Description: Current Stack Name
    Value: !Ref AWS::StackName
  PublicDnsName:
    Description: Public DNS name of the Bastionhost EC2 instance
    Value: !GetAtt BastionhostServer.PublicDnsName
  PublicIpAddress:
    Description: Public IP address of the Bastionhost EC2 instance
    Value: !GetAtt BastionhostServer.PublicIp
  AMIId:
    Description: ImageId of the AMI of Bastionhost instance
    Value: !FindInMap
      - RegionAMIConfig
      - !Ref AWS::Region
      - AMI
  VpcId:
    Description: VPC ID of the Bastionhost EC2 instance
    Value: !GetAtt BastionhostServer.VpcId
  SubnetId:
    Description: Subnet ID of the Bastionhost EC2 instance
    Value: !GetAtt BastionhostServer.SubnetId
  InstanceSecurityGroupId:
    Description: Security Group ID of the Bastionhost EC2 instance
    Value: !ImportValue
      Fn::Sub: ${EnvironmentName}-ec2-security-group-id
