AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Instance Profiles with neccessary permissions

Parameters:
  EnvironmentName:
    Description: Name of the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - test
Resources:
  MyEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-ec2-role
      Description: IAM Role for the EC2 instances
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: SSMParameterStoreAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:GetParametersByPath
                  - ssm:PutParameter
                  - ssm:AddTagsToResource
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2-role
        - Key: Environment
          Value: !Ref EnvironmentName
  MyEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${EnvironmentName}-ec2-instance-profile
      Path: /
      Roles:
        - !Ref MyEC2Role

Outputs:
  AccountId:
    Description: AWS Account ID
    Value: !Ref AWS::AccountId
  RegionName:
    Description: AWS Region Name
    Value: !Ref AWS::Region
  StackId:
    Description: Current Stack ID
    Value: !Ref AWS::StackId
  StackName:
    Description: Current Stack Name
    Value: !Ref AWS::StackName
  Environment:
    Description: Environment Name
    Value: !Ref EnvironmentName
    Export:
      Name: !Sub ${EnvironmentName}-environment-name
  EC2Role:
    Description: EC2 Role Name
    Value: !Ref MyEC2Role
  InstanceProfile:
    Description: EC2 Instance Profile
    Value: !Ref MyEC2InstanceProfile
    Export:
      Name: !Sub ${EnvironmentName}-ec2-instance-profile